import React from "react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import styles from "./layout.module.css";

export const metadata = {
	title: "Handshakes",
	description: "Generated by Next.js",
};

export default function Layout(props: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={styles.root}>
				<AppRouterCacheProvider>
					{props.children}
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
